version: '3.9'
services: 
  client: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:alpine
    container_name: client
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
