name: AppVerdinho Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d --build
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Heroku Docker Container Deploy
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "app-verdinho-pagamento" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}