name: AppVerdinho Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: cd app && docker-compose up -d --build
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm run install:apps
      - name: Run tests
        run: npm test
